### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by WOLFIE-OG** [idiidk/kahoot-tools#20]
How to host on a server like a raspberry pi 2b

**Comment by IncognitoJam** [comment]
**You cannot do this on the old Raspberry Pi Model B, B+ or Pi Zero! It will only work on the Pi 2 and Pi 3 Model B boards which have ARMv7+**

Assuming you already have Raspbian on your Pi, you need to install `git` ([Git](https://git-scm.com/)) and `nodejs` ([Node.js](https://nodejs.org/en/)) You can do this from the command line.

Open a terminal and run these commands:
- `sudo apt update`
This command will update the package lists on your Pi so that it knows where to download packages you want to install in the future and what the latest versions are.
- `sudo apt install -y git`
You can install `git` using `apt`.
- `curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -`
This command adds the NodeSource repository to apt on your Pi.
- `sudo apt install -y nodejs`
Lastly you can install `nodejs` with `apt`!

To check that your installation is working run `node -v` and it should print out something like this:
```
$ node -v
v11.6.0
```

Now that you have `git` and `nodejs` installed you can follow the normal installation instructions!

https://github.com/idiidk/kahoot-tools#installation

**Comment by WOLFIE-OG** [comment]
thx

**Comment by idiidk** [comment]
Thanks @IncognitoJam
